name: pr-checker

on:
  pull_request:
    branches: [ main, develop]    # main / develop 브랜치에 PR 보낼 때 실행
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # JDK Setup
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: application.yml 생성
        run: |
          mkdir -p ./src/main/resources && cd $_
          touch ./application.yml
          echo "${{ secrets.YML }}" > ./application.yml
          cat ./application.yml

      - name: application-prod.yml 생성
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.YML_PROD }}" > ./application-prod.yml

        # Gradle Wrapper 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

        # Gradle Test를 실행한다
      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Lint Check
        run: ./gradlew ktlintCheck -PcompileSdkVersion=34